routes:
  - path: /github
    target: https://example.com/webhook

    headers:
      Authorization: "Bearer {{ header `X-Token` }}"
      X-Event: "{{ header `X-GitHub-Event` }}"

    body: |
      {
        "repository": "{{ escape (body `repository.name`) }}",
        "sender": "{{ escape (body `sender.login`) }}",
        "action": "{{ escape (body `action`) }}"
      }

  - path: /slack
    target: https://example.com/slack

    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ env `API_TOKEN` `dummy-token` }}"

    body: |
      {
        "text": "{{ escape (body `message.text`) }}"
      }

  - path: /discord
    target: ${DISCORD_WEBHOOK_URL}

    headers:
      Content-Type: application/json

    body: |
      {
        "content": "GitHub event: {{ header `X-GitHub-Event` }}\n```json\n{{ escape (toPrettyJson (body)) }}\n```"
      }